// @vitest-environment happy-dom
import { writeFileSync } from 'node:fs';
import { describe, it } from 'vitest';
import { RichEditor } from '../src/editor';
import { CORPUS } from './corpus';

/**
 * Generates SUPPORT.md: the measured normalization table the improvement plan
 * demands before implementation acceptance. Re-run whenever the editor
 * dependencies change; commit the diff, it IS the support table.
 */
describe('support table generation', () => {
  it('writes SUPPORT.md', async () => {
    const lines: string[] = [
      '# Rich-mode normalization support table',
      '',
      'Generated by `tests/support-table.test.ts` from the checked-in corpus.',
      'Do not hand-edit. "Load emits change" must always be no: a view-only',
      'open/close must never touch the source. "Round-trip" describes what a',
      'real user edit does to the bytes.',
      '',
      '| Fixture | Load emits change | Round-trip |',
      '|---|---|---|',
    ];

    for (const fixture of CORPUS) {
      const root = document.createElement('div');
      document.body.appendChild(root);
      let changes = 0;
      const editor = await RichEditor.mount(root, {
        markdown: fixture.input,
        placeholder: '',
        onChange: () => changes++,
        onOpenLink: () => {},
      });
      await new Promise((r) => setTimeout(r, 20));
      const out = editor.getMarkdown();
      const roundTrip =
        out === fixture.input ? 'exact' : `normalized (expect: ${fixture.expect})`;
      lines.push(`| ${fixture.name} | ${changes > 0 ? 'YES — BUG' : 'no'} | ${roundTrip} |`);
      await editor.destroy();
      root.remove();
    }
    lines.push('');

    writeFileSync('SUPPORT.md', lines.join('\n'));
  });
});
